spring:
  application:
    name: mall-order
  cloud:
    nacos:
      discovery:
        server-addr: my.server.com:8848
        # nacos server endpoint , 用于nacos server 扩所容
#        endpoint: xx.xx.xx

server:
  port: 8081

